/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        // Kinetic vibrant palette
        "outline-variant": "#e1bfb5",
        "tertiary": "#3b6a00",
        "surface-container-high": "#e8e8ea",
        "secondary-fixed-dim": "#5ed5f3",
        "on-surface": "#1a1c1e",
        "on-primary-container": "#5f1900",
        "surface-bright": "#f9f9fc",
        "on-primary-fixed-variant": "#832600",
        "inverse-primary": "#ffb59d",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#004e5d",
        "primary-fixed": "#ffdbd0",
        "surface-tint": "#ab3500",
        "on-error": "#ffffff",
        "primary-container": "#ff6b35",
        "inverse-on-surface": "#f0f0f3",
        "on-tertiary-fixed-variant": "#2b5000",
        "surface-dim": "#dadadc",
        "surface": "#f9f9fc",
        "secondary-fixed": "#adecff",
        "error-container": "#ffdad6",
        "outline": "#8d7168",
        "primary": "#ab3500",
        "on-primary-fixed": "#390c00",
        "surface-variant": "#e2e2e5",
        "on-error-container": "#93000a",
        "inverse-surface": "#2f3133",
        "on-surface-variant": "#594139",
        "tertiary-container": "#68ab1d",
        "on-tertiary-container": "#1d3900",
        "surface-container": "#eeeef0",
        "secondary": "#00687b",
        "surface-container-low": "#f3f3f6",
        "on-tertiary-fixed": "#0e2000",
        "on-background": "#1a1c1e",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#001f26",
        "secondary-container": "#6be1ff",
        "tertiary-fixed": "#aef764",
        "primary-fixed-dim": "#ffb59d",
        "surface-container-highest": "#e2e2e5",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#93da4b",
        "on-secondary-container": "#006375",
        "background": "#f9f9fc",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        // Legacy compatibility
        "glass-white": "rgba(255, 255, 255, 0.7)",
        "surface-gray": "#F2F2F7",
        "success-green": "#34C759",
        "danger-red": "#FF3B30",
      },
      borderRadius: {
        DEFAULT: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "glass-padding": "16px",
        "unit": "4px",
        "gutter": "12px",
        "stack-md": "8px",
        "stack-sm": "4px",
        "stack-lg": "16px",
        "gutter-md": "12px",
        base: "8px",
      },
      fontFamily: {
        "body-md": ["Hanken Grotesk", "Inter", "system-ui", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "Inter", "system-ui", "sans-serif"],
        "display-xl": ["Sora", "Hanken Grotesk", "system-ui", "sans-serif"],
        "display-lg": ["Sora", "Hanken Grotesk", "system-ui", "sans-serif"],
        "label-sm": ["JetBrains Mono", "Inter", "system-ui", "sans-serif"],
        "label-md": ["JetBrains Mono", "Inter", "system-ui", "sans-serif"],
        "label-caps": ["JetBrains Mono", "Inter", "system-ui", "sans-serif"],
        "headline-lg": ["Sora", "Hanken Grotesk", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Sora", "Hanken Grotesk", "system-ui", "sans-serif"],
        "headline-md": ["Sora", "Hanken Grotesk", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "body-lg": ["17px", { lineHeight: "26px", fontWeight: "400" }],
        "display-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-caps": ["10px", { lineHeight: "14px", letterSpacing: "0.1em", fontWeight: "500" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "headline-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
      },
      boxShadow: {
        "kinetic": "0 10px 25px rgba(171, 53, 0, 0.4)",
        "bottom-glow": "0px -20px 40px rgba(255, 107, 53, 0.15)",
      },
      animation: {
        ripple: "ripple 3s infinite",
      },
      keyframes: {
        ripple: {
          "0%": { transform: "scale(1)", opacity: "0.8" },
          "100%": { transform: "scale(2.5)", opacity: "0" },
        },
      },
    },
  },
  plugins: [],
}
