/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#001f28",
        "on-tertiary-container": "#003744",
        "secondary-fixed-dim": "#ffb875",
        "tertiary-fixed": "#b5ebff",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#594139",
        "inverse-on-surface": "#f3f0f2",
        "surface-container-high": "#eae7ea",
        "secondary": "#8d4f00",
        "on-secondary": "#ffffff",
        "on-surface": "#1b1b1d",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#ffb59d",
        "glass-white": "rgba(255, 255, 255, 0.7)",
        "tertiary-container": "#00a7cb",
        "surface-container-low": "#f6f3f5",
        "secondary-fixed": "#ffdcc0",
        "inverse-surface": "#303032",
        "outline": "#8d7168",
        "error": "#ba1a1a",
        "background": "#fcf8fb",
        "on-error-container": "#93000a",
        "surface-gray": "#F2F2F7",
        "inverse-primary": "#ffb59d",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#390c00",
        "on-secondary-fixed": "#2d1600",
        "on-primary": "#ffffff",
        "primary-fixed": "#ffdbd0",
        "surface-tint": "#ab3500",
        "on-primary-container": "#5f1900",
        "surface-variant": "#e4e2e4",
        "on-secondary-container": "#663800",
        "secondary-container": "#fe9824",
        "on-tertiary-fixed-variant": "#004e60",
        "success-green": "#34C759",
        "on-background": "#1b1b1d",
        "on-primary-fixed-variant": "#832600",
        "outline-variant": "#e1bfb5",
        "tertiary-fixed-dim": "#59d5fb",
        "surface-container": "#f0edef",
        "tertiary": "#00677e",
        "danger-red": "#FF3B30",
        "surface": "#fcf8fb",
        "surface-container-highest": "#e4e2e4",
        "surface-bright": "#fcf8fb",
        "on-secondary-fixed-variant": "#6b3b00",
        "primary": "#ab3500",
        "surface-dim": "#dcd9dc",
        "primary-container": "#ff6b35",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "stack-md": "12px",
        "stack-sm": "4px",
        "stack-lg": "24px",
        "gutter-md": "16px",
        base: "8px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Hanken Grotesk"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "30px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
