spring:
  application:
    name: voice-accounting
  # Spring AI - DeepSeek
  ai:
    openai:
      api-key: sk-a13d527015e54ad9bb76ab7b0ceb1e30
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7
  datasource:
    url: jdbc:mysql://mysql:3306/db_voice_accounting?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root@XH2001!
  data:
    redis:
      host: redis
      port: 6379
      password: root@XH2001!
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  mail:
    host: smtp.163.com
    port: 994
    username: 18365404517@163.com
    password: NPRDDKVXCLILSNQP
    protocol: smtps
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          starttls:
            enable: true
        debug: false

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.hfh.api.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 阿里云智能语音交互配置
aliyun:
  nls:
    app-key: nUZFPlJcV0JTuLXY
    access-key-id: LTAI5t99pCFWCwYgy4YJZs9d
    access-key-secret: hFQkHai2pacVrNr7kVYkJhIuLfDDbx

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '管理端接口'
      paths-to-match: '/admin/**'
      packages-to-scan: com.hfh.api.admin.controller
    - group: '用户端接口'
      paths-to-match: '/api/**'
      packages-to-scan: com.hfh.api.user.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表

sa-token:
  token-name: Authorization
  timeout: 7200
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false
